import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Button } from "@/components/ui/button";
import Link from "next/link";
import { HomeIcon, PlusIcon, UserIcon } from "lucide-react";
import { Input } from "@/components/ui/input";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        // Add overflow-hidden class
        className={`${geistSans.variable} ${geistMono.variable} antialiased overflow-hidden`}
      >
        {/* Add fixed header */}
        {/* Update header className */}
        <header className="fixed top-0 w-full shadow bg-background h-[72px] px-8 flex items-center justify-between z-10">
          <div className="bg-primary-500 w-[68px] h-[32px] bg-primary text-white rounded-full flex items-center justify-center cursor-pointer">
            <Link href="/">小红书</Link>
          </div>
          <Input
            placeholder="搜索"
            className="w-[300px] h-[32px] rounded-full focus-visible:ring-0 focus-visible:ring-shadow-none focus-visible:outline-none"
          />
          <div className="flex items-center gap-4">
            <Link href="/">创作中心</Link>
            <Link href="/">业务合作</Link>
          </div>
        </header>
        {/* Add main content area with flex layout */}
        {/* Change pt-[72px] to mt-[72px] */}
        <main className="flex h-[calc(100vh_-_72px)] mt-[72px]">
          {/* Add sidebar */}
          {/* Update sidebar content and add h-full */}
          <div className="h-full w-[266px] bg-background shadow">
            <div className="text-primary-500 flex flex-col items-start justify-center gap-4 mt-4 px-4">
              <Link
                href="/"
                className="flex items-center gap-2 hover:bg-muted rounded-full w-full p-4"
              >
                <HomeIcon /> 首页
              </Link>
              <Link
                href="/publish"
                className="flex items-center gap-2 hover:bg-muted rounded-full w-full p-4"
              >
                <UserIcon /> 发布页面
              </Link>
              <Link
                href="/music"
                className="flex items-center gap-2 hover:bg-muted rounded-full w-full p-4"
              >
                <UserIcon /> 音乐
              </Link>
              <Button className="flex items-center gap-2 hover:bg-primary/50 rounded-full w-full h-[48px]">
                发帖
              </Button>
          </div>
            {/* Remove previous span and div */}
          </div>
          {/* Main content area that takes remaining space */}
          {/* Add h-full and overflow-y-auto */}
          <div className="flex-1 h-full overflow-y-auto">{children}</div>
        </main>
      </body>
    </html>
  );
}
