
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
// Link and Input might not be needed here anymore
// import Link from "next/link";
// import { Input } from "@/components/ui/input";
import { SidebarNav } from "@/components/layout/SidebarNav";
import { Header } from "@/components/layout/Header"; // Import the new Header component

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

// Metadata can likely be moved out if layout becomes a server component again
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased overflow-hidden`}
      >
        {/* Use the new Header component */}
        <Header />
        {/* Removed the old header block */}

        {/* Add main content area with flex layout */}
        <main className="flex h-[calc(100vh_-_72px)] mt-[72px]">
          {/* Sidebar container */}
          <div className="h-full w-[266px] bg-background shadow">
            <SidebarNav />
          </div>
          {/* Main content area */}
          <div className="flex-1 h-full overflow-y-auto">{children}</div>
        </main>
      </body>
    </html>
  );
}
